# -*- coding: utf-8 -*-
"""
Created on 2022-01-03
---------
@summary: An UpdateItem for RFD topics
---------
@author: Kelvin
"""

from feapder import Item, UpdateItem


class RfdTopicItem(UpdateItem):
    """
    This class was generated by feapder.
    command: feapder create -i spider_data.
    """
    __update_key__ = [
        "total_up",
        "total_down",
        "upvotes",
        "total_replies",
        "total_views",
        "elapsed_mins",
    ] # Update certain keys

    def __init__(self, *args, **kwargs):
        self.topic_id = None
        self.upvotes = None
        self.elapsed_mins = None
        self.dealer_name = None
        self.topic_title = None
        self.post_time = None
        self.total_up = None
        self.total_down = None
        self.total_replies = None
        self.total_views = None
        self.offer_price = None
        self.topic_title_link = None
        self.summary_body = None
        self.post_time_str = None
        self.last_post_time = None
        self.offer = None
        self.offer_url = None
        self.offer_savings = None
        self.offer_expires_at = None
