# -*- coding: utf-8 -*-
"""
Created on 2022-01-03
---------
@summary: An UpdateItem for RFD topics
---------
@author: Kelvin
"""

from feapder import Item, UpdateItem


class RfdTopicItem(UpdateItem):
    """
    This class was generated by feapder.
    command: feapder create -i spider_data.
    """
    __update_key__ = [
        "total_up",
        "total_down",
        "upvotes",
        "total_replies",
        "total_views",
        "elapsed_mins",
        "msg_sent_cnt",
    ] # Update certain keys

    def __init__(self, *args, **kwargs):
        topic = args[0]
        
        self.topic_id = topic.topic_id
        self.upvotes = topic.upvotes
        self.elapsed_mins = topic.elapsed_mins
        self.dealer_name = topic.dealer_name
        self.topic_title = topic.topic_title
        self.post_time = topic.post_time
        self.total_up = topic.total_up
        self.total_down = topic.total_down
        self.total_replies = topic.total_replies
        self.total_views = topic.total_views
        self.offer_price = topic.offer_price
        self.topic_title_link = topic.topic_title_link
        self.summary_body = topic.summary_body
        self.post_time_str = topic.post_time_str
        self.last_post_time = topic.last_post_time
        self.offer = topic.offer
        self.offer_url = topic.offer_url
        self.offer_savings = topic.offer_savings
        self.offer_expires_at = topic.offer_expires_at
        self.msg_sent_cnt = None
