# -*- coding: utf-8 -*-
"""
Created on 2021-03-10 17:28:36
---------
@summary:
---------
@author: Boris
"""

from feapder import Item, UpdateItem


class SpiderDataItem(UpdateItem):
    """
    This class was generated by feapder.
    command: feapder create -i spider_data.
    """
    __update_key__ = [
        "upvotes",
        "elapsed_mins",
        "reply_count",
        "view_count",
        "msg_sent_cnt"
    ] # Update certain keys

    def __init__(self, *args, **kwargs):
        self._id = None # type : int(7) unsigned | allow_null : NO | key : PRI | default_value : None | extra : auto_increment | column_comment :
        self.upvotes = None
        # self.upvotes_per_min = None
        self.elapsed_mins = None
        self.retailer_name = None
        self.topic_title = None
        self.first_post_time_obj = None
        self.first_post_time = None
        self.reply_count = None
        self.view_count = None
        self.msg_sent_cnt = None
        self.topic_link = None