# -*- coding: utf-8 -*-
"""
Created on 2021-11-29 17:28:36
---------
@summary:
---------
@author: Kelvin
"""

from feapder import Item, UpdateItem


class SpiderDataItem(UpdateItem):
    """
    This class was generated by feapder.
    command: feapder create -i spider_data.
    """
    # __update_key__ = [
    #     "upvotes",
    #     "elapsed_mins",
    #     "reply_count",
    #     "view_count",
    #     "msg_sent_cnt"
    # ] # Update certain keys

    def __init__(self, *args, **kwargs):
        self.thread_id = None
        self.upvotes = None

        self.elapsed_mins = None
        self.retailer_name = None
        self.topic_title = None
        self.first_post_time_obj = None
        self.first_post_time = None
        self.reply_count = None
        self.view_count = None
        self.msg_sent_cnt = None
        self.topic_link = None


class BBMongoItem(UpdateItem):
    """
    This class was generated by feapder.
    command: feapder create -i spider_data.
    """

    def __init__(self, *args, **kwargs):
        self.sku = None
        self.shipping_quantity = None
        self.shipping_status = None
        self.seller_id = None
        self.pickup_status = None
        self.rmd_hill_quantity = None
        self.pickup_locations = None
        